// <auto-generated />
namespace MyApp.SqlServerModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class address_county_changed_to_country : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(address_county_changed_to_country));
        
        string IMigrationMetadata.Id
        {
            get { return "201805162104337_address_county_changed_to_country"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
