// <auto-generated />
namespace MyApp.SqlServerModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class title_not_required_in_contact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(title_not_required_in_contact));
        
        string IMigrationMetadata.Id
        {
            get { return "201805171007573_title_not_required_in_contact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
